set -g default-terminal "tmux-256color"
set -sa terminal-features ',xterm-256color:RGB'
set -g default-command "bash --login"
set -g mouse off
set -g history-limit 50000
set -g escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
